name: Cleanup Artifacts

on:
  schedule:
    - cron: '0 0 * * 0' # Runs every Sunday at midnight
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.7

    - name: List and delete old artifacts
      uses: actions/github-script@v6
      with:
        script: |
          const daysOld = 30;
          const cutoff = new Date();
          cutoff.setDate(cutoff.getDate() - daysOld);

          const artifacts = await github.paginate('GET /repos/{owner}/{repo}/actions/artifacts', {
            owner: context.repo.owner,
            repo: context.repo.repo
          });

          for (const artifact of artifacts) {
            const createdAt = new Date(artifact.created_at);
            if (createdAt < cutoff) {
              await github.request('DELETE /repos/{owner}/{repo}/actions/artifacts/{artifact_id}', {
                owner: context.repo.owner,
                repo: context.repo.repo,
                artifact_id: artifact.id
              });
              console.log(`Deleted artifact: ${artifact.name} (ID: ${artifact.id})`);
            }
          }